project:
  type: website
  output-dir: docs
  resources:
    - video-player/video-player-demo.mov

website:
  title: "R Bites"
  navbar:
    left:
      - about.qmd
        
      - text: "Bites"
        icon: fa-cookie-bite
        menu:
          - text: "Console Video Player"
            icon: file-earmark-play
            href: video-player/video-player.qmd
          - text: "R on a Flip Phone"
            icon: terminal-fill
            href: flipphone-r/flipphone-r.html
      
format:
  html:
    theme: [cosmo, monocode.scss]
    css: styles.css
    toc: true
      
#ref: https://yihui.org/rmarkdown/rmarkdown-site
#styles: yuenhsu.com/posts/highlight-styles.html#monokai


  